/**
 * Fleetsure — PDF Document Generator
 * ────────────────────────────────────
 * Generates PDFs for: Payment Receipt, Freight Invoice, Letterhead, Monthly Statement.
 * Uses PDFKit (pure Node.js, no headless browser).
 */
import PDFDocument from 'pdfkit'

// ── Shared constants ────────────────────────────────────────────────────────

const COLORS = {
  primary: '#1e3a5f',
  accent: '#2563eb',
  text: '#1e293b',
  muted: '#64748b',
  light: '#f1f5f9',
  border: '#cbd5e1',
  white: '#ffffff',
}

const PAGE_MARGIN = 50
const CONTENT_WIDTH = 595.28 - PAGE_MARGIN * 2 // A4 width minus margins

// ── Helpers ─────────────────────────────────────────────────────────────────

function formatCurrency(amount) {
  const num = Number(amount) || 0
  return '₹' + num.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

function formatDate(dateStr) {
  if (!dateStr) return new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
  return new Date(dateStr).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
}

function drawHorizontalLine(doc, y, color = COLORS.border) {
  doc.strokeColor(color).lineWidth(0.5)
    .moveTo(PAGE_MARGIN, y)
    .lineTo(595.28 - PAGE_MARGIN, y)
    .stroke()
}

// ── Common Header (company branding) ────────────────────────────────────────

function drawHeader(doc, tenantInfo, docTitle) {
  const companyName = tenantInfo?.name || 'Fleet Company'
  const address = tenantInfo?.address || ''
  const city = tenantInfo?.city || ''
  const phone = tenantInfo?.phone || ''
  const gstin = tenantInfo?.gstin || ''

  // Company name
  doc.fontSize(20).fillColor(COLORS.primary).font('Helvetica-Bold')
    .text(companyName, PAGE_MARGIN, PAGE_MARGIN, { width: CONTENT_WIDTH })

  // Address line
  let infoY = doc.y + 4
  const infoParts = [address, city].filter(Boolean).join(', ')
  if (infoParts) {
    doc.fontSize(9).fillColor(COLORS.muted).font('Helvetica')
      .text(infoParts, PAGE_MARGIN, infoY, { width: CONTENT_WIDTH })
    infoY = doc.y + 2
  }

  // Phone & GSTIN line
  const detailParts = []
  if (phone) detailParts.push(`Phone: ${phone}`)
  if (gstin) detailParts.push(`GSTIN: ${gstin}`)
  if (detailParts.length) {
    doc.fontSize(9).fillColor(COLORS.muted).font('Helvetica')
      .text(detailParts.join('  |  '), PAGE_MARGIN, infoY, { width: CONTENT_WIDTH })
    infoY = doc.y + 2
  }

  // Horizontal rule
  const lineY = infoY + 8
  drawHorizontalLine(doc, lineY, COLORS.primary)

  // Document title
  doc.fontSize(14).fillColor(COLORS.accent).font('Helvetica-Bold')
    .text(docTitle, PAGE_MARGIN, lineY + 12, { width: CONTENT_WIDTH, align: 'center' })

  return doc.y + 16
}

// ── Common Footer ───────────────────────────────────────────────────────────

function drawFooter(doc, tenantInfo) {
  const bottomY = 780
  drawHorizontalLine(doc, bottomY, COLORS.border)
  doc.fontSize(7).fillColor(COLORS.muted).font('Helvetica')
    .text('This is a computer-generated document.', PAGE_MARGIN, bottomY + 6, { width: CONTENT_WIDTH, align: 'center' })
  const companyName = tenantInfo?.name || 'Fleet Company'
  doc.text(`${companyName} — Generated by Fleetsure`, PAGE_MARGIN, bottomY + 16, { width: CONTENT_WIDTH, align: 'center' })
}

// ── Field row helper ────────────────────────────────────────────────────────

function drawFieldRow(doc, label, value, y, options = {}) {
  const labelWidth = options.labelWidth || 140
  doc.fontSize(10).fillColor(COLORS.muted).font('Helvetica')
    .text(label, PAGE_MARGIN, y, { width: labelWidth })
  doc.fontSize(10).fillColor(COLORS.text).font('Helvetica-Bold')
    .text(String(value || '-'), PAGE_MARGIN + labelWidth, y, { width: CONTENT_WIDTH - labelWidth })
  return y + 20
}

// ── Table helper ────────────────────────────────────────────────────────────

function drawTable(doc, headers, rows, startY) {
  const colWidths = headers.map(h => h.width)
  let y = startY

  // Header row
  doc.rect(PAGE_MARGIN, y, CONTENT_WIDTH, 22).fill(COLORS.primary)
  let x = PAGE_MARGIN
  headers.forEach((h, i) => {
    doc.fontSize(9).fillColor(COLORS.white).font('Helvetica-Bold')
      .text(h.label, x + 6, y + 6, { width: colWidths[i] - 12, align: h.align || 'left' })
    x += colWidths[i]
  })
  y += 22

  // Data rows
  rows.forEach((row, rowIdx) => {
    const bgColor = rowIdx % 2 === 0 ? COLORS.white : COLORS.light
    doc.rect(PAGE_MARGIN, y, CONTENT_WIDTH, 20).fill(bgColor)

    x = PAGE_MARGIN
    headers.forEach((h, i) => {
      doc.fontSize(9).fillColor(COLORS.text).font('Helvetica')
        .text(String(row[h.key] ?? '-'), x + 6, y + 5, { width: colWidths[i] - 12, align: h.align || 'left' })
      x += colWidths[i]
    })
    y += 20
  })

  // Bottom border
  drawHorizontalLine(doc, y, COLORS.border)
  return y + 8
}

// ═══════════════════════════════════════════════════════════════════════════
// 1. PAYMENT RECEIPT
// ═══════════════════════════════════════════════════════════════════════════

export function generatePaymentReceipt(data, tenantInfo) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: PAGE_MARGIN })
    const buffers = []
    doc.on('data', b => buffers.push(b))
    doc.on('end', () => resolve(Buffer.concat(buffers)))
    doc.on('error', reject)

    let y = drawHeader(doc, tenantInfo, 'PAYMENT RECEIPT')

    // Receipt details box
    doc.rect(PAGE_MARGIN, y, CONTENT_WIDTH, 28).fill(COLORS.light)
    doc.fontSize(10).fillColor(COLORS.text).font('Helvetica-Bold')
      .text(`Receipt No: ${data.receiptNumber || 'PR-' + Date.now()}`, PAGE_MARGIN + 10, y + 8, { width: CONTENT_WIDTH / 2 })
    doc.fontSize(10).fillColor(COLORS.text).font('Helvetica')
      .text(`Date: ${formatDate(data.date)}`, PAGE_MARGIN + CONTENT_WIDTH / 2, y + 8, { width: CONTENT_WIDTH / 2 - 10, align: 'right' })
    y += 44

    // Fields
    y = drawFieldRow(doc, 'Paid To', data.paidTo, y)
    y = drawFieldRow(doc, 'Amount', formatCurrency(data.amount), y)
    y = drawFieldRow(doc, 'Purpose', data.purpose, y)
    y = drawFieldRow(doc, 'Payment Mode', data.paymentMode || 'Cash', y)
    if (data.referenceNumber) {
      y = drawFieldRow(doc, 'Reference / Txn No.', data.referenceNumber, y)
    }

    // Amount in words box
    y += 10
    doc.rect(PAGE_MARGIN, y, CONTENT_WIDTH, 30).fill(COLORS.light)
    doc.fontSize(9).fillColor(COLORS.muted).font('Helvetica')
      .text('Amount (in words):', PAGE_MARGIN + 10, y + 4)
    doc.fontSize(10).fillColor(COLORS.text).font('Helvetica-Bold')
      .text(numberToWords(Number(data.amount) || 0) + ' Rupees Only', PAGE_MARGIN + 10, y + 16, { width: CONTENT_WIDTH - 20 })
    y += 44

    // Notes
    if (data.notes) {
      doc.fontSize(9).fillColor(COLORS.muted).font('Helvetica').text('Notes:', PAGE_MARGIN, y)
      y += 14
      doc.fontSize(10).fillColor(COLORS.text).font('Helvetica').text(data.notes, PAGE_MARGIN, y, { width: CONTENT_WIDTH })
      y = doc.y + 10
    }

    // Signature area
    y = Math.max(y + 60, 650)
    doc.fontSize(9).fillColor(COLORS.muted).font('Helvetica')
      .text('Authorized Signatory', 595.28 - PAGE_MARGIN - 150, y, { width: 150, align: 'center' })
    drawHorizontalLine(doc, y - 4, COLORS.border)

    drawFooter(doc, tenantInfo)
    doc.end()
  })
}

// ═══════════════════════════════════════════════════════════════════════════
// 2. FREIGHT INVOICE
// ═══════════════════════════════════════════════════════════════════════════

export function generateFreightInvoice(data, tenantInfo) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: PAGE_MARGIN })
    const buffers = []
    doc.on('data', b => buffers.push(b))
    doc.on('end', () => resolve(Buffer.concat(buffers)))
    doc.on('error', reject)

    let y = drawHeader(doc, tenantInfo, 'FREIGHT INVOICE')

    // Invoice meta
    doc.rect(PAGE_MARGIN, y, CONTENT_WIDTH, 28).fill(COLORS.light)
    doc.fontSize(10).fillColor(COLORS.text).font('Helvetica-Bold')
      .text(`Invoice No: ${data.invoiceNumber || 'FI-' + Date.now()}`, PAGE_MARGIN + 10, y + 8, { width: CONTENT_WIDTH / 2 })
    doc.fontSize(10).fillColor(COLORS.text).font('Helvetica')
      .text(`Date: ${formatDate(data.date)}`, PAGE_MARGIN + CONTENT_WIDTH / 2, y + 8, { width: CONTENT_WIDTH / 2 - 10, align: 'right' })
    y += 44

    // Bill To
    doc.fontSize(10).fillColor(COLORS.muted).font('Helvetica').text('Bill To:', PAGE_MARGIN, y)
    y += 14
    doc.fontSize(11).fillColor(COLORS.text).font('Helvetica-Bold').text(data.billTo || '-', PAGE_MARGIN, y)
    y += 14
    if (data.billToAddress) {
      doc.fontSize(9).fillColor(COLORS.muted).font('Helvetica').text(data.billToAddress, PAGE_MARGIN, y, { width: CONTENT_WIDTH })
      y = doc.y + 6
    }
    y += 10

    // Trip details table
    const items = data.items || [{
      description: `Freight: ${data.origin || '-'} → ${data.destination || '-'}`,
      vehicle: data.vehicleNumber || '-',
      distance: data.distance ? `${data.distance} km` : '-',
      rate: data.freightRate ? formatCurrency(data.freightRate) : '-',
      amount: formatCurrency(data.freightAmount || data.amount || 0),
    }]

    const headers = [
      { label: '#', key: 'sno', width: 30, align: 'center' },
      { label: 'Description', key: 'description', width: 195 },
      { label: 'Vehicle', key: 'vehicle', width: 80 },
      { label: 'Distance', key: 'distance', width: 60, align: 'right' },
      { label: 'Rate', key: 'rate', width: 65, align: 'right' },
      { label: 'Amount', key: 'amount', width: 65, align: 'right' },
    ]

    const rows = items.map((it, i) => ({ sno: i + 1, ...it }))
    y = drawTable(doc, headers, rows, y)

    // Totals
    const subtotal = Number(data.freightAmount || data.amount || 0)
    const gstRate = Number(data.gstPercent || 0)
    const gstAmount = subtotal * gstRate / 100
    const total = subtotal + gstAmount

    y += 4
    const totalsX = 595.28 - PAGE_MARGIN - 200
    const drawTotalRow = (label, value, bold = false) => {
      const font = bold ? 'Helvetica-Bold' : 'Helvetica'
      const size = bold ? 12 : 10
      doc.fontSize(size).fillColor(COLORS.text).font(font)
        .text(label, totalsX, y, { width: 120, align: 'right' })
      doc.fontSize(size).fillColor(COLORS.text).font(font)
        .text(value, totalsX + 125, y, { width: 75, align: 'right' })
      y += bold ? 22 : 18
    }

    drawTotalRow('Subtotal', formatCurrency(subtotal))
    if (gstRate > 0) {
      drawTotalRow(`GST (${gstRate}%)`, formatCurrency(gstAmount))
    }
    drawHorizontalLine(doc, y - 4, COLORS.border)
    drawTotalRow('Total', formatCurrency(total), true)

    // Notes
    if (data.notes) {
      y += 10
      doc.fontSize(9).fillColor(COLORS.muted).font('Helvetica').text('Notes:', PAGE_MARGIN, y)
      y += 14
      doc.fontSize(9).fillColor(COLORS.text).font('Helvetica').text(data.notes, PAGE_MARGIN, y, { width: CONTENT_WIDTH })
    }

    drawFooter(doc, tenantInfo)
    doc.end()
  })
}

// ═══════════════════════════════════════════════════════════════════════════
// 3. LETTERHEAD
// ═══════════════════════════════════════════════════════════════════════════

export function generateLetterhead(data, tenantInfo) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: PAGE_MARGIN })
    const buffers = []
    doc.on('data', b => buffers.push(b))
    doc.on('end', () => resolve(Buffer.concat(buffers)))
    doc.on('error', reject)

    let y = drawHeader(doc, tenantInfo, '')

    // Date and reference
    doc.fontSize(10).fillColor(COLORS.text).font('Helvetica')
      .text(`Date: ${formatDate(data.date)}`, PAGE_MARGIN, y, { width: CONTENT_WIDTH })
    y = doc.y + 4
    if (data.referenceNumber) {
      doc.fontSize(10).fillColor(COLORS.text).font('Helvetica')
        .text(`Ref: ${data.referenceNumber}`, PAGE_MARGIN, y, { width: CONTENT_WIDTH })
      y = doc.y + 4
    }
    y += 12

    // To
    if (data.to) {
      doc.fontSize(10).fillColor(COLORS.muted).font('Helvetica').text('To,', PAGE_MARGIN, y)
      y += 14
      doc.fontSize(10).fillColor(COLORS.text).font('Helvetica').text(data.to, PAGE_MARGIN, y, { width: CONTENT_WIDTH })
      y = doc.y + 16
    }

    // Subject
    if (data.subject) {
      doc.fontSize(11).fillColor(COLORS.text).font('Helvetica-Bold')
        .text(`Subject: ${data.subject}`, PAGE_MARGIN, y, { width: CONTENT_WIDTH })
      y = doc.y + 16
    }

    // Body text
    if (data.body) {
      doc.fontSize(10).fillColor(COLORS.text).font('Helvetica')
        .text(data.body, PAGE_MARGIN, y, { width: CONTENT_WIDTH, lineGap: 4 })
    }

    drawFooter(doc, tenantInfo)
    doc.end()
  })
}

// ═══════════════════════════════════════════════════════════════════════════
// 4. MONTHLY STATEMENT
// ═══════════════════════════════════════════════════════════════════════════

export function generateMonthlyStatement(data, tenantInfo) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: PAGE_MARGIN, bufferPages: true })
    const buffers = []
    doc.on('data', b => buffers.push(b))
    doc.on('end', () => resolve(Buffer.concat(buffers)))
    doc.on('error', reject)

    let y = drawHeader(doc, tenantInfo, 'MONTHLY STATEMENT')

    // Period
    doc.rect(PAGE_MARGIN, y, CONTENT_WIDTH, 28).fill(COLORS.light)
    doc.fontSize(10).fillColor(COLORS.text).font('Helvetica-Bold')
      .text(`Period: ${formatDate(data.startDate)} — ${formatDate(data.endDate)}`, PAGE_MARGIN + 10, y + 8, { width: CONTENT_WIDTH - 20 })
    y += 44

    // Summary box
    const summaryItems = [
      { label: 'Total Trips', value: String(data.totalTrips || 0) },
      { label: 'Total Revenue', value: formatCurrency(data.totalRevenue || 0) },
      { label: 'Total Expenses', value: formatCurrency(data.totalExpenses || 0) },
      { label: 'Net Profit', value: formatCurrency((data.totalRevenue || 0) - (data.totalExpenses || 0)) },
    ]

    const boxWidth = CONTENT_WIDTH / 4
    summaryItems.forEach((item, i) => {
      const bx = PAGE_MARGIN + i * boxWidth
      doc.rect(bx, y, boxWidth, 50).fill(i === 3 ? COLORS.primary : COLORS.light)
      doc.fontSize(8).fillColor(i === 3 ? '#94a3b8' : COLORS.muted).font('Helvetica')
        .text(item.label, bx + 8, y + 8, { width: boxWidth - 16 })
      doc.fontSize(14).fillColor(i === 3 ? COLORS.white : COLORS.text).font('Helvetica-Bold')
        .text(item.value, bx + 8, y + 24, { width: boxWidth - 16 })
    })
    y += 66

    // Trip list table
    if (data.trips && data.trips.length > 0) {
      doc.fontSize(11).fillColor(COLORS.text).font('Helvetica-Bold')
        .text('Trip Details', PAGE_MARGIN, y)
      y += 18

      const tripHeaders = [
        { label: '#', key: 'sno', width: 28, align: 'center' },
        { label: 'Date', key: 'date', width: 72 },
        { label: 'Vehicle', key: 'vehicle', width: 75 },
        { label: 'Route', key: 'route', width: 150 },
        { label: 'Distance', key: 'distance', width: 55, align: 'right' },
        { label: 'Revenue', key: 'revenue', width: 60, align: 'right' },
        { label: 'Profit', key: 'profit', width: 55, align: 'right' },
      ]

      const tripRows = data.trips.slice(0, 25).map((t, i) => ({
        sno: i + 1,
        date: formatDate(t.startDate || t.date),
        vehicle: t.vehicleNumber || t.vehicle || '-',
        route: `${t.origin || '-'} → ${t.destination || '-'}`,
        distance: t.distance ? `${t.distance} km` : '-',
        revenue: formatCurrency(t.freightAmount || t.revenue || 0),
        profit: formatCurrency((t.freightAmount || t.revenue || 0) - (t.totalExpenses || t.expenses || 0)),
      }))

      y = drawTable(doc, tripHeaders, tripRows, y)
    }

    // Vehicle-wise breakdown
    if (data.vehicleBreakdown && data.vehicleBreakdown.length > 0) {
      y += 10
      if (y > 650) { doc.addPage(); y = PAGE_MARGIN }

      doc.fontSize(11).fillColor(COLORS.text).font('Helvetica-Bold')
        .text('Vehicle-wise Breakdown', PAGE_MARGIN, y)
      y += 18

      const vHeaders = [
        { label: 'Vehicle', key: 'vehicle', width: 120 },
        { label: 'Trips', key: 'trips', width: 50, align: 'center' },
        { label: 'Distance', key: 'distance', width: 80, align: 'right' },
        { label: 'Revenue', key: 'revenue', width: 90, align: 'right' },
        { label: 'Expenses', key: 'expenses', width: 80, align: 'right' },
        { label: 'Profit', key: 'profit', width: 75, align: 'right' },
      ]

      y = drawTable(doc, vHeaders, data.vehicleBreakdown, y)
    }

    drawFooter(doc, tenantInfo)
    doc.end()
  })
}


// ── Number to words (Indian style, up to crores) ────────────────────────────

function numberToWords(n) {
  if (n === 0) return 'Zero'
  const ones = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine',
    'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen']
  const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety']

  const intPart = Math.floor(Math.abs(n))
  if (intPart === 0) return 'Zero'

  function twoDigit(num) {
    if (num < 20) return ones[num]
    return tens[Math.floor(num / 10)] + (num % 10 ? ' ' + ones[num % 10] : '')
  }

  function threeDigit(num) {
    if (num >= 100) return ones[Math.floor(num / 100)] + ' Hundred' + (num % 100 ? ' ' + twoDigit(num % 100) : '')
    return twoDigit(num)
  }

  let result = ''
  let rem = intPart

  if (rem >= 10000000) {
    result += threeDigit(Math.floor(rem / 10000000)) + ' Crore '
    rem %= 10000000
  }
  if (rem >= 100000) {
    result += twoDigit(Math.floor(rem / 100000)) + ' Lakh '
    rem %= 100000
  }
  if (rem >= 1000) {
    result += twoDigit(Math.floor(rem / 1000)) + ' Thousand '
    rem %= 1000
  }
  if (rem > 0) {
    result += threeDigit(rem)
  }

  return result.trim()
}
